---
title: "Siyasal Katılım ve Kişilik Özellikleri İnternet Anketi Çalışması"  
---

<br>

Araştırmamızın internet sayfasına hoşgeldiniz! 

Koç Üniversitesi'nde siyasal katılım ve kişilik özellikleri ilişkisini irdeleyen ve 2019.291.IRB3.149 no'lu etik kurul kararının izninde Türkiye genelinde gerçekleştirilmesi planlanan bilimsel bir araştırmanın ön çalışmasını yapmaktayız.

Bu ön çalışma bir internet anketi niteliğindedir. Çalışmamızın nihai hedefi kişilik özellikleri, siyasal tutum ve davranışlar özelinde hazırlanan taslak soru cetvellerinin test edilmesi ve rastlantısal olmayan internet anketi örnekleminde ölçümlenmesidir.

Eğer izin verirseniz size yaklaşık 10 dakika sürecek birkaç soru sormak isteriz. Bu sorulara vereceğiniz cevaplar hiçbir zaman sizin isminizle birlikte kullanılmayacak, kişisel bilgileriniz tamamen gizli tutulacaktır. Bu çalışmanın içinde olmak isteyip istemediğinize tamamen kendi iradenizle ve etki altında kalmadan karar vermeniz önemlidir. Katılmaya karar verdikten sonra, herhangi bir anda, sahip olduğunuz herhangi bir hakkı kaybetmeden veya herhangi bir yaptırıma maruz kalmadan istediğiniz zaman anketimizden ayrılabilirsiniz.
 
Bu görüşme sizden Türkiye’de sosyal tercihler ile alakalı birçok konu hakkındaki düşüncelerinizi ifade etmenizi istemektedir. Burada doğru veya yanlış cevap yoktur, sadece bize her bir konu hakkında ne düşündüğünüzü açık olarak ifade etmenizi rica ediyoruz. 

Yardımlarınız ve ilginiz için teşekkür ederiz. Saygılarımızla,

<b> Anketimize katılmak için lütfen buraya tıklayınız.</b>

---

<br>

<b><i>Not:</i></b> Bu araştırma ile ilgili herhangi bir sorunuz veya endişeniz varsa, lütfen iletişime geçiniz:

Fatih Erol

Koç Üniversitesi, Uluslararası İlişkiler Bölümü

Doktora Araştırma ve Öğretim Asistanı

E-posta Adresi: ferol15@ku.edu.tr

Araştırma İnternet Sayfası: http://kisilikozellikleri.com



